// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using linc.Data;

#nullable disable

namespace linc.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240414100638_JournalMessageArguments")]
    partial class JournalMessageArguments
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ApplicationDocumentApplicationDossier", b =>
                {
                    b.Property<int>("DocumentsId")
                        .HasColumnType("int")
                        .HasColumnName("documents_id");

                    b.Property<int>("DossiersId")
                        .HasColumnType("int")
                        .HasColumnName("dossiers_id");

                    b.HasKey("DocumentsId", "DossiersId")
                        .HasName("pk_application_document_application_dossier");

                    b.HasIndex("DossiersId")
                        .HasDatabaseName("ix_application_document_application_dossier_dossiers_id");

                    b.ToTable("application_document_application_dossier", (string)null);
                });

            modelBuilder.Entity("ApplicationDocumentApplicationIssue", b =>
                {
                    b.Property<int>("FilesId")
                        .HasColumnType("int")
                        .HasColumnName("files_id");

                    b.Property<int>("IssuesId")
                        .HasColumnType("int")
                        .HasColumnName("issues_id");

                    b.HasKey("FilesId", "IssuesId")
                        .HasName("pk_application_document_application_issue");

                    b.HasIndex("IssuesId")
                        .HasDatabaseName("ix_application_document_application_issue_issues_id");

                    b.ToTable("application_document_application_issue", (string)null);
                });

            modelBuilder.Entity("linc.Data.ApplicationDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_created");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("document_type");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("extension");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("varchar(127)")
                        .HasColumnName("file_name");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_updated");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("mime_type");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("relative_path");

                    b.HasKey("Id")
                        .HasName("pk_documents");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("linc.Data.ApplicationDossier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("AssignedToId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("assigned_to_id");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_created");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("last_name");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_updated");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_dossiers");

                    b.HasIndex("AssignedToId")
                        .HasDatabaseName("ix_dossiers_assigned_to_id");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_dossiers_created_by_id");

                    b.ToTable("dossiers", (string)null);
                });

            modelBuilder.Entity("linc.Data.ApplicationIssue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_created");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("description");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_available");

                    b.Property<int>("IssueNumber")
                        .HasColumnType("int")
                        .HasColumnName("issue_number");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_updated");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int")
                        .HasColumnName("release_year");

                    b.HasKey("Id")
                        .HasName("pk_issues");

                    b.ToTable("issues", (string)null);
                });

            modelBuilder.Entity("linc.Data.ApplicationLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Culture")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("culture");

                    b.HasKey("Id")
                        .HasName("pk_languages");

                    b.HasIndex("Culture")
                        .IsUnique()
                        .HasDatabaseName("ix_languages_culture");

                    b.ToTable("languages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Culture = "bg"
                        },
                        new
                        {
                            Id = 2,
                            Culture = "en"
                        });
                });

            modelBuilder.Entity("linc.Data.ApplicationSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("AuthorId")
                        .HasMaxLength(127)
                        .HasColumnType("varchar(127)")
                        .HasColumnName("author_id");

                    b.Property<string>("AuthorNames")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("author_names");

                    b.Property<string>("AuthorNotes")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("author_notes");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_created");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("first_name");

                    b.Property<int>("IssueId")
                        .HasColumnType("int")
                        .HasColumnName("issue_id");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int")
                        .HasColumnName("language_id");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("last_name");

                    b.Property<int>("LastPage")
                        .HasColumnType("int")
                        .HasColumnName("last_page");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_updated");

                    b.Property<int>("PdfId")
                        .HasColumnType("int")
                        .HasColumnName("pdf_id");

                    b.Property<int>("StartingPage")
                        .HasColumnType("int")
                        .HasColumnName("starting_page");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("title");

                    b.Property<string>("TitleNotes")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("title_notes");

                    b.HasKey("Id")
                        .HasName("pk_sources");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_sources_author_id");

                    b.HasIndex("FirstName")
                        .HasDatabaseName("ix_sources_first_name");

                    b.HasIndex("IssueId")
                        .HasDatabaseName("ix_sources_issue_id");

                    b.HasIndex("LanguageId")
                        .HasDatabaseName("ix_sources_language_id");

                    b.HasIndex("LastName")
                        .HasDatabaseName("ix_sources_last_name");

                    b.HasIndex("PdfId")
                        .IsUnique()
                        .HasDatabaseName("ix_sources_pdf_id");

                    b.ToTable("sources", (string)null);
                });

            modelBuilder.Entity("linc.Data.ApplicationStringResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("EditedById")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("edited_by_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("key");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int")
                        .HasColumnName("language_id");

                    b.Property<DateTime>("LastEdited")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_edited");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_string_resources");

                    b.HasIndex("EditedById")
                        .HasDatabaseName("ix_string_resources_edited_by_id");

                    b.HasIndex("Key")
                        .HasDatabaseName("ix_string_resources_key");

                    b.HasIndex("LanguageId")
                        .HasDatabaseName("ix_string_resources_language_id");

                    b.ToTable("string_resources", (string)null);
                });

            modelBuilder.Entity("linc.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("AvatarType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("avatar_type");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_created");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("description");

                    b.Property<bool>("DisplayEmail")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("display_email");

                    b.Property<int>("DisplayNameType")
                        .HasMaxLength(127)
                        .HasColumnType("int")
                        .HasColumnName("display_name_type");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FacebookAvatarPath")
                        .HasColumnType("longtext")
                        .HasColumnName("facebook_avatar_path");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("first_name");

                    b.Property<string>("GoogleAvatarPath")
                        .HasColumnType("longtext")
                        .HasColumnName("google_avatar_path");

                    b.Property<string>("InternalAvatarPath")
                        .HasColumnType("longtext")
                        .HasColumnName("internal_avatar_path");

                    b.Property<bool>("IsAuthor")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_author");

                    b.Property<bool>("IsReviewer")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_reviewer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("last_name");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_updated");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("Subscribed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("subscribed");

                    b.Property<string>("TwitterAvatarPath")
                        .HasColumnType("longtext")
                        .HasColumnName("twitter_avatar_path");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("asp_net_users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000000",
                            AccessFailedCount = 0,
                            AvatarType = "Gravatar",
                            ConcurrencyStamp = "00000000-0000-0000-0000-000000000000",
                            DateCreated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "System administrator. / Администратор на системата.",
                            DisplayEmail = true,
                            DisplayNameType = 2,
                            Email = "admin-linc@uni-plovdiv.bg",
                            EmailConfirmed = true,
                            FirstName = "Panayot",
                            IsAuthor = false,
                            IsReviewer = false,
                            LastName = "Ivanov",
                            LastUpdated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN-LINC@UNI-PLOVDIV.BG",
                            NormalizedUserName = "P.IVANOV",
                            PasswordHash = "CHANGE_ME",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "00000000-0000-0000-0000-000000000000",
                            Subscribed = false,
                            TwoFactorEnabled = false,
                            UserName = "p.ivanov"
                        });
                });

            modelBuilder.Entity("linc.Data.DossierJournal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_created");

                    b.Property<int>("DossierId")
                        .HasColumnType("int")
                        .HasColumnName("dossier_id");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_updated");

                    b.Property<string>("Message")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("message");

                    b.Property<string>("MessageArguments")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("message_arguments");

                    b.Property<string>("PerformedById")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("performed_by_id");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_dossier_journals");

                    b.HasIndex("DossierId")
                        .HasDatabaseName("ix_dossier_journals_dossier_id");

                    b.HasIndex("Message")
                        .HasDatabaseName("ix_dossier_journals_message");

                    b.HasIndex("PerformedById")
                        .HasDatabaseName("ix_dossier_journals_performed_by_id");

                    b.ToTable("dossier_journals", (string)null);
                });

            modelBuilder.Entity("linc.Data.IssueJournal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_created");

                    b.Property<int>("IssueId")
                        .HasColumnType("int")
                        .HasColumnName("issue_id");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_updated");

                    b.Property<string>("Message")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("message");

                    b.Property<string>("MessageArguments")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("message_arguments");

                    b.Property<string>("PerformedById")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("performed_by_id");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_issue_journals");

                    b.HasIndex("IssueId")
                        .HasDatabaseName("ix_issue_journals_issue_id");

                    b.HasIndex("Message")
                        .HasDatabaseName("ix_issue_journals_message");

                    b.HasIndex("PerformedById")
                        .HasDatabaseName("ix_issue_journals_performed_by_id");

                    b.ToTable("issue_journals", (string)null);
                });

            modelBuilder.Entity("linc.Data.SourceJournal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_updated");

                    b.Property<string>("Message")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("message");

                    b.Property<string>("MessageArguments")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("message_arguments");

                    b.Property<string>("PerformedById")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("performed_by_id");

                    b.Property<int>("SourceId")
                        .HasColumnType("int")
                        .HasColumnName("source_id");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_source_journals");

                    b.HasIndex("Message")
                        .HasDatabaseName("ix_source_journals_message");

                    b.HasIndex("PerformedById")
                        .HasDatabaseName("ix_source_journals_performed_by_id");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_source_journals_source_id");

                    b.ToTable("source_journals", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("asp_net_roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000000",
                            ConcurrencyStamp = "000000000000-0000-0000-0000-00000000",
                            Name = "ADMINISTRATOR",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "5e1199d7-7725-4900-aa34-5496365bf5a0",
                            ConcurrencyStamp = "0a5fb5636945-43aa-0094-5277-7d9911e5",
                            Name = "HEAD_EDITOR",
                            NormalizedName = "HEAD_EDITOR"
                        },
                        new
                        {
                            Id = "05cbe4c7-108e-40bc-bee7-65438875026e",
                            ConcurrencyStamp = "e62057883456-7eeb-cb04-e801-7c4ebc50",
                            Name = "EDITOR",
                            NormalizedName = "EDITOR"
                        },
                        new
                        {
                            Id = "6b1acea8-2d26-4c82-b6ad-7281b7d621ae",
                            ConcurrencyStamp = "ea126d7b1827-da6b-28c4-62d2-8aeca1b6",
                            Name = "USER_PLUS",
                            NormalizedName = "USER_PLUS"
                        },
                        new
                        {
                            Id = "90667439-9058-4956-96e6-d23bac481443",
                            ConcurrencyStamp = "344184cab32d-6e69-6594-8509-93476609",
                            Name = "USER",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext")
                        .HasColumnName("claim_value");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("asp_net_role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext")
                        .HasColumnName("claim_value");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("asp_net_user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(127)
                        .HasColumnType("varchar(127)")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(127)
                        .HasColumnType("varchar(127)")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("asp_net_user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("asp_net_user_roles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "00000000-0000-0000-0000-000000000000",
                            RoleId = "00000000-0000-0000-0000-000000000000"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(127)
                        .HasColumnType("varchar(127)")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasMaxLength(127)
                        .HasColumnType("varchar(127)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("longtext")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("asp_net_user_tokens", (string)null);
                });

            modelBuilder.Entity("ApplicationDocumentApplicationDossier", b =>
                {
                    b.HasOne("linc.Data.ApplicationDocument", null)
                        .WithMany()
                        .HasForeignKey("DocumentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_document_application_dossier_documents_documents");

                    b.HasOne("linc.Data.ApplicationDossier", null)
                        .WithMany()
                        .HasForeignKey("DossiersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_document_application_dossier_dossiers_dossiers_id");
                });

            modelBuilder.Entity("ApplicationDocumentApplicationIssue", b =>
                {
                    b.HasOne("linc.Data.ApplicationDocument", null)
                        .WithMany()
                        .HasForeignKey("FilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_document_application_issue_documents_files_id");

                    b.HasOne("linc.Data.ApplicationIssue", null)
                        .WithMany()
                        .HasForeignKey("IssuesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_document_application_issue_issues_issues_id");
                });

            modelBuilder.Entity("linc.Data.ApplicationDossier", b =>
                {
                    b.HasOne("linc.Data.ApplicationUser", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToId")
                        .HasConstraintName("fk_dossiers_users_assigned_to_id");

                    b.HasOne("linc.Data.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dossiers_users_created_by_id");

                    b.Navigation("AssignedTo");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("linc.Data.ApplicationSource", b =>
                {
                    b.HasOne("linc.Data.ApplicationUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .HasConstraintName("fk_sources_users_author_id");

                    b.HasOne("linc.Data.ApplicationIssue", "Issue")
                        .WithMany("Sources")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sources_issues_issue_id");

                    b.HasOne("linc.Data.ApplicationLanguage", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sources_languages_language_id");

                    b.HasOne("linc.Data.ApplicationDocument", "Pdf")
                        .WithOne("Source")
                        .HasForeignKey("linc.Data.ApplicationSource", "PdfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sources_documents_pdf_id");

                    b.Navigation("Author");

                    b.Navigation("Issue");

                    b.Navigation("Language");

                    b.Navigation("Pdf");
                });

            modelBuilder.Entity("linc.Data.ApplicationStringResource", b =>
                {
                    b.HasOne("linc.Data.ApplicationUser", "EditedBy")
                        .WithMany()
                        .HasForeignKey("EditedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_string_resources_users_edited_by_id");

                    b.HasOne("linc.Data.ApplicationLanguage", "Language")
                        .WithMany("StringResources")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_string_resources_languages_language_id");

                    b.Navigation("EditedBy");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("linc.Data.DossierJournal", b =>
                {
                    b.HasOne("linc.Data.ApplicationDossier", "Dossier")
                        .WithMany("Journals")
                        .HasForeignKey("DossierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dossier_journals_dossiers_dossier_id");

                    b.HasOne("linc.Data.ApplicationUser", "PerformedBy")
                        .WithMany()
                        .HasForeignKey("PerformedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dossier_journals_users_performed_by_id");

                    b.Navigation("Dossier");

                    b.Navigation("PerformedBy");
                });

            modelBuilder.Entity("linc.Data.IssueJournal", b =>
                {
                    b.HasOne("linc.Data.ApplicationIssue", "Issue")
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_journals_issues_issue_id");

                    b.HasOne("linc.Data.ApplicationUser", "PerformedBy")
                        .WithMany()
                        .HasForeignKey("PerformedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_journals_users_performed_by_id");

                    b.Navigation("Issue");

                    b.Navigation("PerformedBy");
                });

            modelBuilder.Entity("linc.Data.SourceJournal", b =>
                {
                    b.HasOne("linc.Data.ApplicationUser", "PerformedBy")
                        .WithMany()
                        .HasForeignKey("PerformedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_source_journals_users_performed_by_id");

                    b.HasOne("linc.Data.ApplicationSource", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_source_journals_sources_source_id");

                    b.Navigation("PerformedBy");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("linc.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("linc.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("linc.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("linc.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("linc.Data.ApplicationDocument", b =>
                {
                    b.Navigation("Source");
                });

            modelBuilder.Entity("linc.Data.ApplicationDossier", b =>
                {
                    b.Navigation("Journals");
                });

            modelBuilder.Entity("linc.Data.ApplicationIssue", b =>
                {
                    b.Navigation("Sources");
                });

            modelBuilder.Entity("linc.Data.ApplicationLanguage", b =>
                {
                    b.Navigation("StringResources");
                });
#pragma warning restore 612, 618
        }
    }
}
