//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace linc.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("linc.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проф. дн Александър Войчех Миколайчак.
        /// </summary>
        public static string Board_Aleksander_Mikołajczak_Member {
            get {
                return ResourceManager.GetString("Board_Aleksander.Mikołajczak_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Кратко описание за члена на редакционния борд. В края да се включи и връзка до допълнителна информация, която е предоставил (напр. orcid)..
        /// </summary>
        public static string Board_Aleksander_Mikołajczak_MemberDescription {
            get {
                return ResourceManager.GetString("Board_Aleksander.Mikołajczak_MemberDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Университет „Адам Мицкевич“, Познан, Полша.
        /// </summary>
        public static string Board_Aleksander_Mikołajczak_MemberWork {
            get {
                return ResourceManager.GetString("Board_Aleksander.Mikołajczak_MemberWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проф. д-р Елизабет Шоре.
        /// </summary>
        public static string Board_Elisabeth_Cheauré_Member {
            get {
                return ResourceManager.GetString("Board_Elisabeth.Cheauré_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Кратко описание за члена на редакционния борд. В края да се включи и връзка до допълнителна информация, която е предоставил (напр. orcid)..
        /// </summary>
        public static string Board_Elisabeth_Cheauré_MemberDescription {
            get {
                return ResourceManager.GetString("Board_Elisabeth.Cheauré_MemberDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Университет „Алберт Лудвиг“, Фрайбург, Германия.
        /// </summary>
        public static string Board_Elisabeth_Cheauré_MemberWork {
            get {
                return ResourceManager.GetString("Board_Elisabeth.Cheauré_MemberWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проф. д-р Хюсеин Мевсим.
        /// </summary>
        public static string Board_Hüseyin_Mevsim_Member {
            get {
                return ResourceManager.GetString("Board_Hüseyin.Mevsim_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Кратко описание за члена на редакционния борд. В края да се включи и връзка до допълнителна информация, която е предоставил (напр. orcid)..
        /// </summary>
        public static string Board_Hüseyin_Mevsim_MemberDescription {
            get {
                return ResourceManager.GetString("Board_Hüseyin.Mevsim_MemberDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анкарски университет, Турция.
        /// </summary>
        public static string Board_Hüseyin_Mevsim_MemberWork {
            get {
                return ResourceManager.GetString("Board_Hüseyin.Mevsim_MemberWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проф. дфн Николай Аретов.
        /// </summary>
        public static string Board_Nikolay_Aretov_Member {
            get {
                return ResourceManager.GetString("Board_Nikolay.Aretov_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Кратко описание за члена на редакционния борд. В края да се включи и връзка до допълнителна информация, която е предоставил (напр. orcid)..
        /// </summary>
        public static string Board_Nikolay_Aretov_MemberDescription {
            get {
                return ResourceManager.GetString("Board_Nikolay.Aretov_MemberDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Институт за литература – Българска академия на науките, София, България.
        /// </summary>
        public static string Board_Nikolay_Aretov_MemberWork {
            get {
                return ResourceManager.GetString("Board_Nikolay.Aretov_MemberWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доц. д-р Саверио Томайоло.
        /// </summary>
        public static string Board_Saverio_Tomaiuolo_Member {
            get {
                return ResourceManager.GetString("Board_Saverio.Tomaiuolo_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Кратко описание за члена на редакционния борд. В края да се включи и връзка до допълнителна информация, която е предоставил (напр. orcid)..
        /// </summary>
        public static string Board_Saverio_Tomaiuolo_MemberDescription {
            get {
                return ResourceManager.GetString("Board_Saverio.Tomaiuolo_MemberDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Университет на Касино и Южен Лацио, Италия.
        /// </summary>
        public static string Board_Saverio_Tomaiuolo_MemberWork {
            get {
                return ResourceManager.GetString("Board_Saverio.Tomaiuolo_MemberWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проф. д-р Суман Гупта.
        /// </summary>
        public static string Board_Suman_Gupta_Member {
            get {
                return ResourceManager.GetString("Board_Suman.Gupta_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Кратко описание за члена на редакционния борд. В края да се включи и връзка до допълнителна информация, която е предоставил (напр. orcid)..
        /// </summary>
        public static string Board_Suman_Gupta_MemberDescription {
            get {
                return ResourceManager.GetString("Board_Suman.Gupta_MemberDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open University, Милтън Кийнс, Великобритания.
        /// </summary>
        public static string Board_Suman_Gupta_MemberWork {
            get {
                return ResourceManager.GetString("Board_Suman.Gupta_MemberWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to гл. ас. д-р Ваня Георгиева.
        /// </summary>
        public static string Board_Vanya_Georgieva_Member {
            get {
                return ResourceManager.GetString("Board_Vanya.Georgieva_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Кратко описание на техническия сътрудник както и допълнителна информация, която е предоставил (напр. orcid)..
        /// </summary>
        public static string Board_Vanya_Georgieva_MemberDescription {
            get {
                return ResourceManager.GetString("Board_Vanya.Georgieva_MemberDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Технически сътрудник &lt;br/&gt;катедра Българска литература и теория на литературата&lt;br/&gt;ПУ „Паисий Хилендарски“.
        /// </summary>
        public static string Board_Vanya_Georgieva_MemberWork {
            get {
                return ResourceManager.GetString("Board_Vanya.Georgieva_MemberWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анализи.
        /// </summary>
        public static string Category_Analyses {
            get {
                return ResourceManager.GetString("Category_Analyses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статии.
        /// </summary>
        public static string Category_Articles {
            get {
                return ResourceManager.GetString("Category_Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хроника.
        /// </summary>
        public static string Category_Chronicles {
            get {
                return ResourceManager.GetString("Category_Chronicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дискусии.
        /// </summary>
        public static string Category_Discussions {
            get {
                return ResourceManager.GetString("Category_Discussions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чуждестранни.
        /// </summary>
        public static string Category_Foreign {
            get {
                return ResourceManager.GetString("Category_Foreign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преглед.
        /// </summary>
        public static string Category_Reviews {
            get {
                return ResourceManager.GetString("Category_Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анкети.
        /// </summary>
        public static string Category_Surveys {
            get {
                return ResourceManager.GetString("Category_Surveys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пловдив 4000, ПУ „Паисий Хилендарски“.
        /// </summary>
        public static string Footer_Address_City {
            get {
                return ResourceManager.GetString("Footer_Address_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to България.
        /// </summary>
        public static string Footer_Address_Country {
            get {
                return ResourceManager.GetString("Footer_Address_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to „Цар Асен“ 24, ет. 3, кабинет 325.
        /// </summary>
        public static string Footer_Address_Street {
            get {
                return ResourceManager.GetString("Footer_Address_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администратор.
        /// </summary>
        public static string Footer_Admin_Label {
            get {
                return ResourceManager.GetString("Footer_Admin_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Footer_Email_Label {
            get {
                return ResourceManager.GetString("Footer_Email_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string Footer_Phone_Label {
            get {
                return ResourceManager.GetString("Footer_Phone_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редакция.
        /// </summary>
        public static string Footer_Redaction_Label {
            get {
                return ResourceManager.GetString("Footer_Redaction_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Footer_Services_Title {
            get {
                return ResourceManager.GetString("Footer_Services_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Етичен кодекс.
        /// </summary>
        public static string Footer_UsefulLinks_Codex {
            get {
                return ResourceManager.GetString("Footer_UsefulLinks_Codex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ползване на бисквитки.
        /// </summary>
        public static string Footer_UsefulLinks_Cookies {
            get {
                return ResourceManager.GetString("Footer_UsefulLinks_Cookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Политика за поверителност.
        /// </summary>
        public static string Footer_UsefulLinks_PrivacyPolicy {
            get {
                return ResourceManager.GetString("Footer_UsefulLinks_PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Процедура по публикуване.
        /// </summary>
        public static string Footer_UsefulLinks_SubmitGuidance {
            get {
                return ResourceManager.GetString("Footer_UsefulLinks_SubmitGuidance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Условия за ползване.
        /// </summary>
        public static string Footer_UsefulLinks_TermsOfService {
            get {
                return ResourceManager.GetString("Footer_UsefulLinks_TermsOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полезни връзки.
        /// </summary>
        public static string Footer_UsefulLinks_Title {
            get {
                return ResourceManager.GetString("Footer_UsefulLinks_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало.
        /// </summary>
        public static string HomeIndex_Title {
            get {
                return ResourceManager.GetString("HomeIndex_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лингвистика, Интерпретация, Концепции.
        /// </summary>
        public static string Logo_Long {
            get {
                return ResourceManager.GetString("Logo_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЛИнК.
        /// </summary>
        public static string Logo_Short {
            get {
                return ResourceManager.GetString("Logo_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За списанието.
        /// </summary>
        public static string NavItem_About {
            get {
                return ResourceManager.GetString("NavItem_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало.
        /// </summary>
        public static string NavItem_Home {
            get {
                return ResourceManager.GetString("NavItem_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Индекс.
        /// </summary>
        public static string NavItem_Index {
            get {
                return ResourceManager.GetString("NavItem_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Брове.
        /// </summary>
        public static string NavItem_Portfolio {
            get {
                return ResourceManager.GetString("NavItem_Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кодекс.
        /// </summary>
        public static string NavItem_Services {
            get {
                return ResourceManager.GetString("NavItem_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Екип.
        /// </summary>
        public static string NavItem_Team {
            get {
                return ResourceManager.GetString("NavItem_Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * процент на постъпилите ръкописи в редакцията спрямо одобрените/публикувани ръкописи в списанието.
        /// </summary>
        public static string Reviews_Message {
            get {
                return ResourceManager.GetString("Reviews_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администратор.
        /// </summary>
        public static string SiteRole_Administrator {
            get {
                return ResourceManager.GetString("SiteRole_Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администратори.
        /// </summary>
        public static string SiteRole_Administrators {
            get {
                return ResourceManager.GetString("SiteRole_Administrators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактор.
        /// </summary>
        public static string SiteRole_Editor {
            get {
                return ResourceManager.GetString("SiteRole_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактори.
        /// </summary>
        public static string SiteRole_Editors {
            get {
                return ResourceManager.GetString("SiteRole_Editors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Борд на редакторите.
        /// </summary>
        public static string SiteRole_EditorsBoard {
            get {
                return ResourceManager.GetString("SiteRole_EditorsBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главен редактор.
        /// </summary>
        public static string SiteRole_HeadEditor {
            get {
                return ResourceManager.GetString("SiteRole_HeadEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главни редактори.
        /// </summary>
        public static string SiteRole_HeadEditors {
            get {
                return ResourceManager.GetString("SiteRole_HeadEditors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребител.
        /// </summary>
        public static string SiteRole_User {
            get {
                return ResourceManager.GetString("SiteRole_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребители.
        /// </summary>
        public static string SiteRole_Users {
            get {
                return ResourceManager.GetString("SiteRole_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to доц. д-р Борян Янев.
        /// </summary>
        public static string Team_B_Yanev_Member {
            get {
                return ResourceManager.GetString("Team_B.Yanev_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Team_B_Yanev_MemberDescription {
            get {
                return ResourceManager.GetString("Team_B.Yanev_MemberDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В редакторския екип на изданието участват преподаватели от факултета, а членове на редакционния борд са изявени изследователи от различни страни и научни организации..
        /// </summary>
        public static string Team_Description {
            get {
                return ResourceManager.GetString("Team_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to доц. д-р Фани Бойкова.
        /// </summary>
        public static string Team_F_Boykova_Member {
            get {
                return ResourceManager.GetString("Team_F.Boykova_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Team_F_Boykova_MemberDescription {
            get {
                return ResourceManager.GetString("Team_F.Boykova_MemberDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to проф. дфн Инна Пелева.
        /// </summary>
        public static string Team_I_Peleva_Member {
            get {
                return ResourceManager.GetString("Team_I.Peleva_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главен редактор „Литература и култура“.
        /// </summary>
        public static string Team_I_Peleva_MemberDescription {
            get {
                return ResourceManager.GetString("Team_I.Peleva_MemberDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to доц. д-р Младен Влашки.
        /// </summary>
        public static string Team_M_Vlashki_Member {
            get {
                return ResourceManager.GetString("Team_M.Vlashki_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Team_M_Vlashki_MemberDescription {
            get {
                return ResourceManager.GetString("Team_M.Vlashki_MemberDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to доц. д-р Снежа Цонева-Матюсън.
        /// </summary>
        public static string Team_S_Mathewson_Member {
            get {
                return ResourceManager.GetString("Team_S.Mathewson_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главен редактор „Език и култура“.
        /// </summary>
        public static string Team_S_Mathewson_MemberDescription {
            get {
                return ResourceManager.GetString("Team_S.Mathewson_MemberDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Екип на &lt;span&gt;списанието&lt;/span&gt;.
        /// </summary>
        public static string Team_SubTitle {
            get {
                return ResourceManager.GetString("Team_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Екип.
        /// </summary>
        public static string Team_Title {
            get {
                return ResourceManager.GetString("Team_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to проф. д-р Вера Маровска.
        /// </summary>
        public static string Team_V_Markovska_Member {
            get {
                return ResourceManager.GetString("Team_V.Markovska_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Team_V_Markovska_MemberDescription {
            get {
                return ResourceManager.GetString("Team_V.Markovska_MemberDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to доц. д-р Яна Роуланд.
        /// </summary>
        public static string Team_Y_Rowland_Member {
            get {
                return ResourceManager.GetString("Team_Y.Rowland_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Team_Y_Rowland_MemberDescription {
            get {
                return ResourceManager.GetString("Team_Y.Rowland_MemberDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to доц. д-р Живко Иванов.
        /// </summary>
        public static string Team_Z_Ivanov_Member {
            get {
                return ResourceManager.GetString("Team_Z.Ivanov_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Team_Z_Ivanov_MemberDescription {
            get {
                return ResourceManager.GetString("Team_Z.Ivanov_MemberDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добре дошли на &lt;span&gt;ЛИнК.uni-plovdiv.bg&lt;/span&gt;.
        /// </summary>
        public static string Welcome_Message {
            get {
                return ResourceManager.GetString("Welcome_Message", resourceCulture);
            }
        }
    }
}
