//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace linc.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("linc.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Съдържание.
        /// </summary>
        public static string AboutSection_Content_Title {
            get {
                return ResourceManager.GetString("AboutSection_Content_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цели и обхват на списанието.
        /// </summary>
        public static string AboutSection_Goals_Title {
            get {
                return ResourceManager.GetString("AboutSection_Goals_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мисия.
        /// </summary>
        public static string AboutSection_Mission_Title {
            get {
                return ResourceManager.GetString("AboutSection_Mission_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Публикуване на ръкопис.
        /// </summary>
        public static string AboutSection_Publish_Title {
            get {
                return ResourceManager.GetString("AboutSection_Publish_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рецензиране.
        /// </summary>
        public static string AboutSection_Review_Title {
            get {
                return ResourceManager.GetString("AboutSection_Review_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Научете повече &lt;span&gt;за списанието&lt;/span&gt;.
        /// </summary>
        public static string AboutSection_SubTitle {
            get {
                return ResourceManager.GetString("AboutSection_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За списанието.
        /// </summary>
        public static string AboutSection_Title {
            get {
                return ResourceManager.GetString("AboutSection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проф. дн Александър Войчех Миколайчак.
        /// </summary>
        public static string Board_Aleksander_Mikołajczak_Member {
            get {
                return ResourceManager.GetString("Board_Aleksander.Mikołajczak_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Университет „Адам Мицкевич“, Познан, Полша.
        /// </summary>
        public static string Board_Aleksander_Mikołajczak_MemberWork {
            get {
                return ResourceManager.GetString("Board_Aleksander.Mikołajczak_MemberWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проф. д-р Елизабет Шоре.
        /// </summary>
        public static string Board_Elisabeth_Cheauré_Member {
            get {
                return ResourceManager.GetString("Board_Elisabeth.Cheauré_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Университет „Алберт Лудвиг“, Фрайбург, Германия.
        /// </summary>
        public static string Board_Elisabeth_Cheauré_MemberWork {
            get {
                return ResourceManager.GetString("Board_Elisabeth.Cheauré_MemberWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проф. д-р Хюсеин Мевсим.
        /// </summary>
        public static string Board_Hüseyin_Mevsim_Member {
            get {
                return ResourceManager.GetString("Board_Hüseyin.Mevsim_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анкарски университет, Турция.
        /// </summary>
        public static string Board_Hüseyin_Mevsim_MemberWork {
            get {
                return ResourceManager.GetString("Board_Hüseyin.Mevsim_MemberWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проф. дфн Николай Аретов.
        /// </summary>
        public static string Board_Nikolay_Aretov_Member {
            get {
                return ResourceManager.GetString("Board_Nikolay.Aretov_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Институт за литература – Българска академия на науките, София, България.
        /// </summary>
        public static string Board_Nikolay_Aretov_MemberWork {
            get {
                return ResourceManager.GetString("Board_Nikolay.Aretov_MemberWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доц. д-р Саверио Томайоло.
        /// </summary>
        public static string Board_Saverio_Tomaiuolo_Member {
            get {
                return ResourceManager.GetString("Board_Saverio.Tomaiuolo_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Университет на Касино и Южен Лацио, Италия.
        /// </summary>
        public static string Board_Saverio_Tomaiuolo_MemberWork {
            get {
                return ResourceManager.GetString("Board_Saverio.Tomaiuolo_MemberWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проф. д-р Суман Гупта.
        /// </summary>
        public static string Board_Suman_Gupta_Member {
            get {
                return ResourceManager.GetString("Board_Suman.Gupta_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open University, Милтън Кийнс, Великобритания.
        /// </summary>
        public static string Board_Suman_Gupta_MemberWork {
            get {
                return ResourceManager.GetString("Board_Suman.Gupta_MemberWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to гл. ас. д-р Ваня Георгиева.
        /// </summary>
        public static string Board_Vanya_Georgieva_Member {
            get {
                return ResourceManager.GetString("Board_Vanya.Georgieva_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Технически сътрудник &lt;br/&gt;катедра Българска литература и теория на литературата&lt;br/&gt;ПУ „Паисий Хилендарски“.
        /// </summary>
        public static string Board_Vanya_Georgieva_MemberWork {
            get {
                return ResourceManager.GetString("Board_Vanya.Georgieva_MemberWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разгледайте списанието по &lt;span&gt;категории&lt;/span&gt;.
        /// </summary>
        public static string CategoriesSection_SubTitle {
            get {
                return ResourceManager.GetString("CategoriesSection_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категории.
        /// </summary>
        public static string CategoriesSection_Title {
            get {
                return ResourceManager.GetString("CategoriesSection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всички.
        /// </summary>
        public static string Category_All {
            get {
                return ResourceManager.GetString("Category_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анализи.
        /// </summary>
        public static string Category_Analyses {
            get {
                return ResourceManager.GetString("Category_Analyses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статии.
        /// </summary>
        public static string Category_Articles {
            get {
                return ResourceManager.GetString("Category_Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хроника.
        /// </summary>
        public static string Category_Chronicles {
            get {
                return ResourceManager.GetString("Category_Chronicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дискусии.
        /// </summary>
        public static string Category_Discussions {
            get {
                return ResourceManager.GetString("Category_Discussions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чуждестранни.
        /// </summary>
        public static string Category_Foreign {
            get {
                return ResourceManager.GetString("Category_Foreign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преглед.
        /// </summary>
        public static string Category_Reviews {
            get {
                return ResourceManager.GetString("Category_Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анкети.
        /// </summary>
        public static string Category_Surveys {
            get {
                return ResourceManager.GetString("Category_Surveys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to АВТОРЪТ.
        /// </summary>
        public static string CodexSection_Authors_Title {
            get {
                return ResourceManager.GetString("CodexSection_Authors_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to РЕДАКТОРСКИЯТ ЕКИП.
        /// </summary>
        public static string CodexSection_Editors_Title {
            get {
                return ResourceManager.GetString("CodexSection_Editors_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to РЕЦЕНЗЕНТЪТ.
        /// </summary>
        public static string CodexSection_Reviewers_Title {
            get {
                return ResourceManager.GetString("CodexSection_Reviewers_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прочетете за нашия &lt;span&gt;Етичен кодекс&lt;/span&gt;.
        /// </summary>
        public static string CodexSection_SubTitle {
            get {
                return ResourceManager.GetString("CodexSection_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кодекс.
        /// </summary>
        public static string CodexSection_Title {
            get {
                return ResourceManager.GetString("CodexSection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пловдив 4000, Пловдивско университетско издателство, „Цар Асен“ 24.
        /// </summary>
        public static string ContactSection_Address_Location {
            get {
                return ResourceManager.GetString("ContactSection_Address_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес на Издателя.
        /// </summary>
        public static string ContactSection_Address_Title {
            get {
                return ResourceManager.GetString("ContactSection_Address_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Етичен кодекс.
        /// </summary>
        public static string ContactSection_Codex_Title {
            get {
                return ResourceManager.GetString("ContactSection_Codex_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email за ръкописи.
        /// </summary>
        public static string ContactSection_Review_Email {
            get {
                return ResourceManager.GetString("ContactSection_Review_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Технически изисквания.
        /// </summary>
        public static string ContactSection_Submit_Title {
            get {
                return ResourceManager.GetString("ContactSection_Submit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпрати ръкопис.
        /// </summary>
        public static string ContactSection_SubmitButton_Label {
            get {
                return ResourceManager.GetString("ContactSection_SubmitButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпращане на ръкопис.
        /// </summary>
        public static string ContactSection_SubTitle {
            get {
                return ResourceManager.GetString("ContactSection_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпращане.
        /// </summary>
        public static string ContactSection_Title {
            get {
                return ResourceManager.GetString("ContactSection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всички права запазени.
        /// </summary>
        public static string Copyright_Label {
            get {
                return ResourceManager.GetString("Copyright_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Често Задавани &lt;span&gt;Въпроси&lt;/span&gt;.
        /// </summary>
        public static string FaqSection_SubTitle {
            get {
                return ResourceManager.GetString("FaqSection_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ч.З.В..
        /// </summary>
        public static string FaqSection_Title {
            get {
                return ResourceManager.GetString("FaqSection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Български &amp; Английски.
        /// </summary>
        public static string FeaturedSection_International_Title {
            get {
                return ResourceManager.GetString("FeaturedSection_International_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анонимно рецензиране.
        /// </summary>
        public static string FeaturedSection_Review_Title {
            get {
                return ResourceManager.GetString("FeaturedSection_Review_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпращане на ръкопис.
        /// </summary>
        public static string FeaturedSection_Submit_Title {
            get {
                return ResourceManager.GetString("FeaturedSection_Submit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реномирана редколегия.
        /// </summary>
        public static string FeaturedSection_Team_Title {
            get {
                return ResourceManager.GetString("FeaturedSection_Team_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пловдив 4000, ПУ „Паисий Хилендарски“.
        /// </summary>
        public static string Footer_Address_City {
            get {
                return ResourceManager.GetString("Footer_Address_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to България.
        /// </summary>
        public static string Footer_Address_Country {
            get {
                return ResourceManager.GetString("Footer_Address_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to „Цар Асен“ 24, ет. 3, кабинет 325.
        /// </summary>
        public static string Footer_Address_Street {
            get {
                return ResourceManager.GetString("Footer_Address_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администратор.
        /// </summary>
        public static string Footer_Admin_Label {
            get {
                return ResourceManager.GetString("Footer_Admin_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Footer_Email_Label {
            get {
                return ResourceManager.GetString("Footer_Email_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string Footer_Phone_Label {
            get {
                return ResourceManager.GetString("Footer_Phone_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редакция.
        /// </summary>
        public static string Footer_Redaction_Label {
            get {
                return ResourceManager.GetString("Footer_Redaction_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Footer_Services_Title {
            get {
                return ResourceManager.GetString("Footer_Services_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открийте нас и нашите автори в мрежата..
        /// </summary>
        public static string Footer_Social_Description {
            get {
                return ResourceManager.GetString("Footer_Social_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Партньори.
        /// </summary>
        public static string Footer_Social_Title {
            get {
                return ResourceManager.GetString("Footer_Social_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Препоръчани.
        /// </summary>
        public static string Footer_Suggestions_Title {
            get {
                return ResourceManager.GetString("Footer_Suggestions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Етичен кодекс.
        /// </summary>
        public static string Footer_UsefulLinks_Codex {
            get {
                return ResourceManager.GetString("Footer_UsefulLinks_Codex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ползване на бисквитки.
        /// </summary>
        public static string Footer_UsefulLinks_Cookies {
            get {
                return ResourceManager.GetString("Footer_UsefulLinks_Cookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Политика за поверителност.
        /// </summary>
        public static string Footer_UsefulLinks_PrivacyPolicy {
            get {
                return ResourceManager.GetString("Footer_UsefulLinks_PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Процедура по публикуване.
        /// </summary>
        public static string Footer_UsefulLinks_SubmitGuidance {
            get {
                return ResourceManager.GetString("Footer_UsefulLinks_SubmitGuidance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Условия за ползване.
        /// </summary>
        public static string Footer_UsefulLinks_TermsOfService {
            get {
                return ResourceManager.GetString("Footer_UsefulLinks_TermsOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полезни връзки.
        /// </summary>
        public static string Footer_UsefulLinks_Title {
            get {
                return ResourceManager.GetString("Footer_UsefulLinks_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Научи повече.
        /// </summary>
        public static string GetStarted_Message {
            get {
                return ResourceManager.GetString("GetStarted_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Използване на бисквитки.
        /// </summary>
        public static string HomeCookies_Title {
            get {
                return ResourceManager.GetString("HomeCookies_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало.
        /// </summary>
        public static string HomeIndex_Title {
            get {
                return ResourceManager.GetString("HomeIndex_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Политика за поверителност.
        /// </summary>
        public static string HomePrivacy_Title {
            get {
                return ResourceManager.GetString("HomePrivacy_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, изпратете ни прикачен ръкопис и декларация със съгласие за публикуването му..
        /// </summary>
        public static string HomeSubmit_SubmitButton_Description {
            get {
                return ResourceManager.GetString("HomeSubmit_SubmitButton_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпрати ръкопис.
        /// </summary>
        public static string HomeSubmit_SubmitButton_Label {
            get {
                return ResourceManager.GetString("HomeSubmit_SubmitButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпращане на текст.
        /// </summary>
        public static string HomeSubmit_Title {
            get {
                return ResourceManager.GetString("HomeSubmit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Условия за ползване.
        /// </summary>
        public static string HomeTerms_Title {
            get {
                return ResourceManager.GetString("HomeTerms_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Съдържание.
        /// </summary>
        public static string Issue_IndexPage_Label {
            get {
                return ResourceManager.GetString("Issue_IndexPage_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Допълнителна информация.
        /// </summary>
        public static string Issue_MoreInformation_Label {
            get {
                return ResourceManager.GetString("Issue_MoreInformation_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Брой №.
        /// </summary>
        public static string Issue_Number_Label {
            get {
                return ResourceManager.GetString("Issue_Number_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Библиотека.
        /// </summary>
        public static string LibraryIndex_Title {
            get {
                return ResourceManager.GetString("LibraryIndex_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лингвистика, Интерпретация, Концепции.
        /// </summary>
        public static string Logo_Long {
            get {
                return ResourceManager.GetString("Logo_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЛИнК.
        /// </summary>
        public static string Logo_Short {
            get {
                return ResourceManager.GetString("Logo_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За списанието.
        /// </summary>
        public static string NavItem_About {
            get {
                return ResourceManager.GetString("NavItem_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категории.
        /// </summary>
        public static string NavItem_Categories {
            get {
                return ResourceManager.GetString("NavItem_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпрати.
        /// </summary>
        public static string NavItem_Contact {
            get {
                return ResourceManager.GetString("NavItem_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бисквитки.
        /// </summary>
        public static string NavItem_Cookies {
            get {
                return ResourceManager.GetString("NavItem_Cookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прекрати редакция.
        /// </summary>
        public static string NavItem_EditModeDisable {
            get {
                return ResourceManager.GetString("NavItem_EditModeDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Режим редакция.
        /// </summary>
        public static string NavItem_EditModeEnable {
            get {
                return ResourceManager.GetString("NavItem_EditModeEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало.
        /// </summary>
        public static string NavItem_Home {
            get {
                return ResourceManager.GetString("NavItem_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Индекс.
        /// </summary>
        public static string NavItem_Library {
            get {
                return ResourceManager.GetString("NavItem_Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архив.
        /// </summary>
        public static string NavItem_Library_Archive {
            get {
                return ResourceManager.GetString("NavItem_Library_Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По години.
        /// </summary>
        public static string NavItem_Library_ByYears {
            get {
                return ResourceManager.GetString("NavItem_Library_ByYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string NavItem_Login {
            get {
                return ResourceManager.GetString("NavItem_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изход.
        /// </summary>
        public static string NavItem_Logout {
            get {
                return ResourceManager.GetString("NavItem_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моят профил.
        /// </summary>
        public static string NavItem_MyProfile {
            get {
                return ResourceManager.GetString("NavItem_MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моите ръкописи.
        /// </summary>
        public static string NavItem_MySubmissions {
            get {
                return ResourceManager.GetString("NavItem_MySubmissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Броеве.
        /// </summary>
        public static string NavItem_Portfolio {
            get {
                return ResourceManager.GetString("NavItem_Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поверителност.
        /// </summary>
        public static string NavItem_Privacy {
            get {
                return ResourceManager.GetString("NavItem_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string NavItem_Register {
            get {
                return ResourceManager.GetString("NavItem_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кодекс.
        /// </summary>
        public static string NavItem_Services {
            get {
                return ResourceManager.GetString("NavItem_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ръкописи.
        /// </summary>
        public static string NavItem_Submissions {
            get {
                return ResourceManager.GetString("NavItem_Submissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпращане.
        /// </summary>
        public static string NavItem_Submit {
            get {
                return ResourceManager.GetString("NavItem_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Екип.
        /// </summary>
        public static string NavItem_Team {
            get {
                return ResourceManager.GetString("NavItem_Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правила и условия.
        /// </summary>
        public static string NavItem_Terms {
            get {
                return ResourceManager.GetString("NavItem_Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Абонирайте се за уведомления, когато нов брой на списанието излезе от печат.
        /// </summary>
        public static string NewsletterSection_Description {
            get {
                return ResourceManager.GetString("NewsletterSection_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Абонирай се.
        /// </summary>
        public static string NewsletterSection_SubscribeButton_Label {
            get {
                return ResourceManager.GetString("NewsletterSection_SubscribeButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Абонирайте се за нашия бюлетин.
        /// </summary>
        public static string NewsletterSection_Title {
            get {
                return ResourceManager.GetString("NewsletterSection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всички.
        /// </summary>
        public static string PortfolioSection_Filter_All {
            get {
                return ResourceManager.GetString("PortfolioSection_Filter_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прегледайте досегашните &lt;span&gt;издания&lt;/span&gt; на списанието.
        /// </summary>
        public static string PortfolioSection_SubTitle {
            get {
                return ResourceManager.GetString("PortfolioSection_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Броеве.
        /// </summary>
        public static string PortfolioSection_Title {
            get {
                return ResourceManager.GetString("PortfolioSection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администратор.
        /// </summary>
        public static string SiteRole_Administrator {
            get {
                return ResourceManager.GetString("SiteRole_Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администратори.
        /// </summary>
        public static string SiteRole_Administrators {
            get {
                return ResourceManager.GetString("SiteRole_Administrators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактор.
        /// </summary>
        public static string SiteRole_Editor {
            get {
                return ResourceManager.GetString("SiteRole_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактори.
        /// </summary>
        public static string SiteRole_Editors {
            get {
                return ResourceManager.GetString("SiteRole_Editors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Борд на редакторите.
        /// </summary>
        public static string SiteRole_EditorsBoard {
            get {
                return ResourceManager.GetString("SiteRole_EditorsBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главен редактор.
        /// </summary>
        public static string SiteRole_HeadEditor {
            get {
                return ResourceManager.GetString("SiteRole_HeadEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главни редактори.
        /// </summary>
        public static string SiteRole_HeadEditors {
            get {
                return ResourceManager.GetString("SiteRole_HeadEditors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребител.
        /// </summary>
        public static string SiteRole_User {
            get {
                return ResourceManager.GetString("SiteRole_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребители.
        /// </summary>
        public static string SiteRole_Users {
            get {
                return ResourceManager.GetString("SiteRole_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to доц. д-р Борян Янев.
        /// </summary>
        public static string Team_B_Yanev_Member {
            get {
                return ResourceManager.GetString("Team_B.Yanev_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to доц. д-р Фани Бойкова.
        /// </summary>
        public static string Team_F_Boykova_Member {
            get {
                return ResourceManager.GetString("Team_F.Boykova_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to проф. дфн Инна Пелева.
        /// </summary>
        public static string Team_I_Peleva_Member {
            get {
                return ResourceManager.GetString("Team_I.Peleva_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to доц. д-р Младен Влашки.
        /// </summary>
        public static string Team_M_Vlashki_Member {
            get {
                return ResourceManager.GetString("Team_M.Vlashki_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to доц. д-р Снежа Цонева-Матюсън.
        /// </summary>
        public static string Team_S_Mathewson_Member {
            get {
                return ResourceManager.GetString("Team_S.Mathewson_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Екип на &lt;span&gt;списанието&lt;/span&gt;.
        /// </summary>
        public static string Team_SubTitle {
            get {
                return ResourceManager.GetString("Team_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Екип.
        /// </summary>
        public static string Team_Title {
            get {
                return ResourceManager.GetString("Team_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to проф. д-р Вера Маровска.
        /// </summary>
        public static string Team_V_Markovska_Member {
            get {
                return ResourceManager.GetString("Team_V.Markovska_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to доц. д-р Яна Роуланд.
        /// </summary>
        public static string Team_Y_Rowland_Member {
            get {
                return ResourceManager.GetString("Team_Y.Rowland_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to доц. д-р Живко Иванов.
        /// </summary>
        public static string Team_Z_Ivanov_Member {
            get {
                return ResourceManager.GetString("Team_Z.Ivanov_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to версия.
        /// </summary>
        public static string Version_Label {
            get {
                return ResourceManager.GetString("Version_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добре дошли на &lt;span&gt;ЛИнК.uni-plovdiv.bg&lt;/span&gt;.
        /// </summary>
        public static string Welcome_Message {
            get {
                return ResourceManager.GetString("Welcome_Message", resourceCulture);
            }
        }
    }
}
