name: Auto Version Increment on Merge

on:
  #pull_request:
  push:
    #types: [closed]
    branches:
      - master

permissions:
  contents: write
  
jobs:
  version-increment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set color
      id: random-color-generator
      run: echo "SELECTED_COLOR=green" >> $GITHUB_OUTPUT
    - name: Get color
      run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"
