name: Auto Version Increment on Merge

on:
  pull_request:
    types: [closed]
    branches:
      - master

permissions:
  contents: write
  
jobs:
  version-increment:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up environment
      run: sudo apt-get update && sudo apt-get install -y gawk

    # TODO: this is stupid, use $NEW_VERSION for the actual version
    - name: Check source branch and increment version
      run: |
        SOURCE_BRANCH="${{ github.head_ref }}"
        echo "Source branch is '$SOURCE_BRANCH'."
        
        if [[ "$SOURCE_BRANCH" == release/* ]]; then
          echo "Incrementing major version for release branch"
          echo "NEW_VERSION=true" >> $GITHUB_ENV
        elif [[ "$SOURCE_BRANCH" == feature/* ]]; then
          echo "Incrementing minor version for feature branch"
          echo "NEW_VERSION=true" >> $GITHUB_ENV
          
          awk '/<Version>[0-9]+\.[0-9]+\.[0-9]+<\/Version>/ {
              match($0, /^([ \t]*)<Version>([0-9]+)\.([0-9]+)\.([0-9]+)<\/Version>/, arr)
              new_version=arr[2] "." arr[3]+1 "." arr[4]
              $0 = arr[1] "<Version>" new_version "</Version>"
          } {print}' linc.csproj > tmpfile && mv tmpfile linc.csproj
          
        elif [[ "$SOURCE_BRANCH" == bugfix/* ]]; then
          echo "Incrementing patch version for bugfix branch"
          echo "NEW_VERSION=true" >> $GITHUB_ENV
        else
          echo "Branch is not part of version automation."
        fi      

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v9
      if: env.NEW_VERSION != ''
      with:
        author_name: Admin-Linc
        author_email: admin-linc@uni-plovdiv.bg
        message: 'Auto-incremented version number to ${{ env.NEW_VERSION }}'
        add: '*.csproj'
