name: Auto Version Increment on Merge

on:
  #pull_request:
  push:
    #types: [closed]
    branches:
      - master

permissions:
  contents: write
  
jobs:
  version-increment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    #- name: Set up environment
    #  run: sudo apt-get update && sudo apt-get install -y gawk

    # TODO: this is stupid, use $NEW_VERSION for the actual version
    - name: Check source branch and increment version
      run: |
        SOURCE_BRANCH="${{ github.head_ref }}"
        # File path to the .csproj file
        csproj_file="linc.csproj"
        
        # Extracting the version line from the .csproj file
        version_line=$(grep '<Version>' "$csproj_file")
        
        # Extracting the version number from the line
        current_version=$(echo $version_line | sed -n 's/.*<Version>\(.*\)<\/Version>.*/\1/p')
        echo current_version
