name: Auto Version Increment on Merge

on:
  #pull_request:
  push:
    #types: [closed]
    branches:
      - master

permissions:
  contents: write
  
jobs:
  version-increment:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up environment
      run: sudo apt-get update && sudo apt-get install -y gawk

    # TODO: this is stupid, use $NEW_VERSION for the actual version
    - name: Check source branch and increment version
      run: |
        SOURCE_BRANCH="${{ github.head_ref }}"
        # File path to the .csproj file
        csproj_file="linc.csproj"
        
        # Extracting the version line from the .csproj file
        version_line=$(grep '<Version>' "$csproj_file")
        
        # Extracting the version number from the line
        current_version=$(echo $version_line | sed -n 's/.*<Version>\(.*\)<\/Version>.*/\1/p')
        echo current_version 

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v9
      if: env.NEW_VERSION != ''
      with:
        author_name: Admin-Linc
        author_email: admin-linc@uni-plovdiv.bg
        message: 'Auto-incremented version number to ${{ env.NEW_VERSION }}'
        add: '*.csproj'
