name: Auto Version Increment on Merge

on:
  #pull_request:
  push:
    #types: [closed]
    branches:
      - master

permissions:
  contents: write
  
jobs:
  version-increment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: test1
      id: test1
      run: echo "NEW_VERSION=test" >> $GITHUB_OUTPUT

    - name: test2
      id: test2
      run: echo ${{ steps.vars.outputs.NEW_VERSION }}
    
        
        # Replacing the version in the .csproj file
        sed -i "s/<Version>$current_version<\/Version>/<Version>$new_version<\/Version>/" "$csproj_file"
        
        echo "Updated version to $new_version and set as environment variable."
