name: Auto Version Increment on Merge

on:
  push:    
    branches:
      - master

jobs:
  version-increment:    
    runs-on: ubuntu-latest
    steps:
    
    - name: Set up environment
      run: sudo apt-get update && sudo apt-get install -y gawk

    - name: Check source branch and increment version
      run: |
         awk --help
