name: Auto Version Increment on Merge

on:
  push:    
    branches:
      - master

jobs:
  version-increment:    
    runs-on: ubuntu-latest
    steps:
    
    - name: Set up environment
      run: sudo apt-get update && sudo apt-get install -y gawk

    - name: Check source branch and increment version
      run: |
          ls -a
          awk '/<Version>[0-9]+\.[0-9]+\.[0-9]+<\/Version>/ {
              match($0, /^([ \t]*)<Version>([0-9]+)\.([0-9]+)\.([0-9]+)<\/Version>/, arr)
              new_version=arr[2] "." arr[3]+1 "." arr[4]              
              $0 = arr[1] "<Version>" new_version "</Version>"
          } {print}' linc.csproj > tmpfile && mv tmpfile linc.csproj
          echo "NEW_VERSION=$new_version" >> $GITHUB_ENV
